### ISSUE TITLE
Some German transaltions

### ISSUE THREAD

**Issue by Lyhtande** [manavortex/FurnitureCatalogue#132]
Hello,

this is [Neverlands](https://www.esoui.com/forums/member.php?u=34006) from ESOUI :)

**/locale/de.lua**
I'm waiting for the permission to directly edit the /locale/de.lua.
Here is a [link](https://gist.github.com/Lyhtande/8c3bd4f0b0785b8724eb19d7504d6c7e) to Gist. It's work in progress, since I could not test every use case.

--------------------------------------------
Here are some further proposals:

**/data/AchievementVendors.lua**
Replacement of locations: [File differences report](https://www.circula-orionis.net/marion/files/AchievementVendors.html)

--------------------------------------------
**/data/MiscItemSources.lua**
Miscellaneous replacements: [File differences report](https://www.circula-orionis.net/marion/files/MiscItemSources.html)

--------------------------------------------

**Replacement for the "item craftable info" in Tooltips, when there is a German translation**
**/locale/de.lua** - line 57 -58
```lua
  SI_FURC_STRING_CRAFTABLE_BY = "Herstellbar von ",
  SI_FURC_STRING_CANNOT_CRAFT = "Ihr könnt das noch nicht herstellen",
```

**FurCTooltip.lua** - line 9
```lua
 return text:gsub("nicht herstellen", "|cFF0000nicht herstellen"):gsub("Herstellbar", "|c00FF00Herstellbar")
```

**/FurnitureCatalogue_Export/FurCDataExport.lua** - line 39
```lua
    local knowledge = (known and (FurC.GetCrafterList(itemLink, recipeArray) .. ": "):gsub("Herstellbar von ", ""))
```
--------------------------------------------

**Comment by wookiefriseur** [comment]
Thanks for the translations!

You can use a fork + Pull Request to dev to contribute.
But if you don't mind I can implement your changes manually, so you don't have to do the fork + PR route.

Whatever is more convenient for you.

Regarding the proposals: Nice. I'll have to extract the hardcoded strings first but then I can add those translations as well.

Related: #40

**Comment by Lyhtande** [comment]
I will create a fork and then a pull request, let's see when I'll find the time ;)

**Comment by wookiefriseur** [comment]
Thx a lot!

I'll release it in a few days. Currently extracting some more hardcoded strings.

**Comment by Lyhtande** [comment]
If you have some new strings to translate, let me know, I will then add them.

**Comment by wookiefriseur** [comment]
Most of your translations are live now with #147  @Lyhtande , thanks again :)

We managed to get many of the location strings from the game, so those don't have to be translated anymore.

Let me know if you find any missing ones. Closing this now
