### ISSUE TITLE
default dropdown not working

### ISSUE THREAD

**Issue by manavortex** [manavortex/FurnitureCatalogue#4]
Even though my default settings says that Favorites should be my default, the dropdown is on my craftables instead. Further, my favorites only show items that can be bought or unknown (in the case of turtle trinket from the writ voucher). I'm not really sure when this change happened. I tried rolling back to a previous version, but I still get the same issue. I even tried a clean install, but that didn't help either.

**Comment by wookiefriseur** [comment]
Tried to reproduce it but you probably fixed that one already.

- [X] favourites as default dropdown persists in SavedVars and is loaded properly
- [X] all types of furniture are added (when adding a recipe the furnishing is added instead, nicely solved 👍)

Version: `4.323`
Date: 2022-05-17
