### ISSUE TITLE
Merge items that are sold by multiple traders

### ISSUE THREAD

**Issue by wookiefriseur** [manavortex/FurnitureCatalogue#66]
Some items are sold by multiple vendors and in different locations. Update tool tips to reflect that.

We can merge some common furniture from the Home Goods Furnishers like:
![common furniture](https://github.com/manavortex/FurnitureCatalogue/assets/8905319/2c706636-5267-423a-8966-da56954f2a1d)

Currently we add some furniture multiple times and the most recent DB entry wins and overwrites the others. 
Example: Rohzika being overwritten
![rohzika](https://github.com/manavortex/FurnitureCatalogue/assets/8905319/b6411d9d-50d7-41c5-88cb-51b42a48eebd)

**Comment by manavortex** [comment]
I tried grouping some of them by type-of-vendor, but it wasn't so simple as that, because naturally it doesn't much follow any logic what's sold where. Not "Grocer, Zone 2" or "Grocer, Daggerfall Covenant" or "Grocer, Zone Starting With A" :( 
In the end, I just went with "fuck it, the player will want to know where to buy this item, so give them _one_ reliable source"

**Comment by wookiefriseur** [comment]
Yeah, I'll keep that issue in mind when reworking the DB structure.

It is also nice how ZOS kept changing sources or IDs. 💩

**Comment by manavortex** [comment]
Do love that, yeah 😬 Consistency? Never heard of 'er

It's probably easiest to add a flag to the data if it's shared by multiple vendors. Or hold a list of IDs that are sold by... IDK. Nothing of this is easy. :D

**Comment by wookiefriseur** [comment]
Was able to group most of them (with some leftovers)

```lua
  AF = GetString(SI_FURC_TRADERS_AF), -- Achievement Vendor: Lozotusk, ...
  BGF = GetString(SI_FURC_TRADERS_BGF), -- Battlegrounds Furnishers
  CAF = GetString(SI_FURC_TRADERS_CAF), -- Main Achievement Vendor: Nolenowen, ...
  EVENT = GetString(SI_FURC_TRADERS_EVENT), -- Event Merchant, any capital city: The Impressario
  HGF = GetString(SI_FURC_TRADERS_HGF), -- Home Goods Furnisher: Maladiq, Rohzika, ...
  HOLIDAY = GetString(SI_FURC_TRADERS_HOLIDAY), -- Heralda, Tildannire, ...
  LUXF = GetString(SI_FURC_TRADERS_LUXF), -- Luxury Furnisher: Zanil
```
Works for now, until ZOS decides to change everything 😁, version is live in #147 

Closing :)
